Calculate memory usage for long-run test.
Change-Id: I317fe85c4ba2870c2c804761e8f79e2e9cff0ff4

diff --git a/script/all-utilities b/script/all-utilities
--- a/script/all-utilities
+++ b/script/all-utilities
@@ -157,6 +157,44 @@ __EOF__
   return 0
 }
 
+# Get memory usage from /endpoints_status
+function get_memory_usage() {
+    local server=${1}
+    local local_json=${2}
+    echo > "{local_json}"
+    curl "${server}/endpoints_status" > "${local_json}"
+
+    python -c "import json, sys; obj = json.load(open(\"${local_json}\")); \
+    print obj['processes'][0]['memoryUsage']" \
+      || { echo "Could not extract memory usage from ${local_json}"; return 1; }
+}
+
+# Check Memory Leak.
+function detect_memory_leak() {
+    local start_usage=${1}
+    local second_usage=${2}
+    [[ ${second_usage} -gt 0 ]] \
+      || { echo "Only run test once."; return 0; }
+
+    local memory_increased=${3}
+    echo "Memory Increased (Bytes): ${memory_increased}."
+    (( threshold = 2 * (${second_usage} - ${start_usage}) / 1000000))
+    if [[ ${threshold} -gt 40 ]]; then
+        threshold=40
+    fi
+    if [[ ${threshold} -lt 10 ]]; then
+        threshold=10
+    fi
+    echo "Memory Threshold (MB): ${threshold}."
+
+    if [[ $(( ${memory_increased} / 1000000 )) -gt ${threshold} ]]; then
+        echo "************ Memory leak is detected. *************"
+        return 1
+    else
+        return 0
+    fi
+}
+
 # Extract key from test env json created from
 # script/create-test-env-json script.
 # As an example, from this json
diff --git a/script/linux-grpc-test-long-run b/script/linux-grpc-test-long-run
--- a/script/linux-grpc-test-long-run
+++ b/script/linux-grpc-test-long-run
@@ -140,8 +140,18 @@ RUN_COUNT=0
 GRPC_STRESS_FAILURES=0
 HTTP_STRESS_FAILURES=0
 
+START_MEMORY_USAGE=0
+SECOND_MEMORY_USAGE=0
+INCREASED_MEMORY_USAGE=0
+
+echo "GRPC_HOST: ${GRPC_HOST}"
+STATUS_SERVER=${GRPC_HOST/8001/8090}
+STATUS_SERVER="http://${STATUS_SERVER}"
+echo "STATUS_SERVER: ${STATUS_SERVER}"
+
 # ${ROOT}/test/client/esp_client.py needs to run at that folder.
 pushd ${ROOT}/test/client > /dev/null
+local_json="$(mktemp /tmp/XXXXXX.json)"
 
 while true; do
   echo "Starting test run ${RUN_COUNT} at $(date)."
@@ -150,6 +160,23 @@ while true; do
   #######################
   # Insert tests here
   #######################
+  ((RUN_COUNT++))
+  curr_usage=$(get_memory_usage "${STATUS_SERVER}" "${local_json}") \
+    || error_exit "Could not extract memory usage from ${STATUS_SERVER}"
+  # Record the memory usage for each test run
+  if [[ ${RUN_COUNT} -eq 1 ]]; then
+    START_MEMORY_USAGE=${curr_usage}
+    echo "Start Memory Usage (Bytes): ${START_MEMORY_USAGE}."
+  else
+    INCREASED_MEMORY_USAGE=$((${curr_usage} - ${START_MEMORY_USAGE}))
+    echo "Memory Increased in Test ${RUN_COUNT} (Bytes): ${INCREASED_MEMORY_USAGE}"
+    if [[ ${RUN_COUNT} -eq 2 ]]; then
+      SECOND_MEMORY_USAGE=${curr_usage}
+      echo "Second Memory Usage (Bytes): ${SECOND_MEMORY_USAGE}."
+    fi
+  fi
+
+  python -m json.tool "${local_json}"
 
   # Generating token for each run, that they expire in 1 hour.
   AUTH_TOKEN=$("${ROOT}/client/custom/gen-auth-token.sh" -a "${SERVICE_NAME}")
@@ -158,12 +185,10 @@ while true; do
   if [[ -n ${HTTP_HOST} ]]; then
     grpc_test_transcode || ((HTTP_STRESS_FAILURES++))
   fi
-
   #######################
   # End of test suite
   #######################
 
-  ((RUN_COUNT++))
   # Break if test has run long enough.
   [[ $(date +"%s") -lt ${END_TIME} ]] || break
 done
@@ -172,8 +197,15 @@ popd > /dev/null
 
 echo "Finished ${RUN_COUNT} test runs."
 echo "Failures: pass-through: ${GRPC_STRESS_FAILURES}, transcode: ${HTTP_STRESS_FAILURES}."
+echo "Total Memory Increased (Bytes): ${INCREASED_MEMORY_USAGE}."
+rm "${local_json}"
+
+# We fail the test if memory increase is large.
+detect_memory_leak "${START_MEMORY_USAGE}" "${SECOND_MEMORY_USAGE}" "${INCREASED_MEMORY_USAGE}"
+HAS_MEMORY_LEAK=$?
+echo "memory leak detect: ${HAS_MEMORY_LEAK}"
 
 # Only mark test as failed if any pass-through tests failed.
 # This is to be consistent with other http stress tests.
 # All failure will be analyzed by release-engineers.
-exit ${GRPC_STRESS_FAILURES}
+exit $((${GRPC_STRESS_FAILURES} + ${HAS_MEMORY_LEAK}))
diff --git a/script/linux-test-kb-long-run b/script/linux-test-kb-long-run
--- a/script/linux-test-kb-long-run
+++ b/script/linux-test-kb-long-run
@@ -65,10 +65,15 @@ RUN_COUNT=0
 STRESS_FAILURES=0
 BOOKSTORE_FAILURES=0
 
+START_MEMORY_USAGE=0
+SECOND_MEMORY_USAGE=0
+INCREASED_MEMORY_USAGE=0
+
 #Status server always run in port 8090 and use HTTP protocol.
 STATUS_SERVER=${HOST/8080/8090}
 STATUS_SERVER=${STATUS_SERVER/443/8090}
 STATUS_SERVER=${STATUS_SERVER/https/http}
+local_json="$(mktemp /tmp/XXXXXX.json)"
 
 while true; do
   ((RUN_COUNT++))
@@ -79,6 +84,22 @@ while true; do
 
   echo "Starting test run ${RUN_COUNT} at $(date)."
   echo "Failures so far: Stress: ${STRESS_FAILURES}, Bookstore: ${BOOKSTORE_FAILURES}."
+
+  # Record the memory usage for each test run
+  curr_usage=$(get_memory_usage "${STATUS_SERVER}" "${local_json}") \
+    || error_exit "Could not extract memory usage from ${STATUS_SERVER}"
+  if [[ ${RUN_COUNT} -eq 1 ]]; then
+    START_MEMORY_USAGE=${curr_usage}
+    echo "Start Memory Usage (Bytes): ${START_MEMORY_USAGE}."
+  else
+    INCREASED_MEMORY_USAGE=$((${curr_usage} - ${START_MEMORY_USAGE}))
+    echo "Memory Increased in Test ${RUN_COUNT} (Bytes): ${INCREASED_MEMORY_USAGE}"
+    if [[ ${RUN_COUNT} -eq 2 ]]; then
+      SECOND_MEMORY_USAGE=${curr_usage}
+      echo "Second Memory Usage (Bytes): ${SECOND_MEMORY_USAGE}."
+    fi
+  fi
+  python -m json.tool "${local_json}"
 
   # Generating token for each run, that they expire in 1 hour.
   JWT_TOKEN=`${ROOT}/client/custom/gen-auth-token.sh -a ${SERVICE_NAME}`
@@ -94,8 +115,6 @@ while true; do
 
   echo "Getting endpoints status at $(date)."
 
-  echo "${STATUS_SERVER}/endpoints_status"
-  curl ${STATUS_SERVER}/endpoints_status
 
   echo "Starting stress test at $(date)."
   ./esp_client.py \
@@ -116,11 +135,17 @@ done
 
 echo "Finished ${RUN_COUNT} test runs."
 echo "Failures: Stress: ${STRESS_FAILURES}, Bookstore: ${BOOKSTORE_FAILURES}."
+echo "Total Memory Increased (Bytes): ${INCREASED_MEMORY_USAGE}."
+rm "${local_json}"
 
 RESULT=0
-
-# We only fail the test if all bookstore runs failed.
+# We fail the test if all bookstore runs failed.
 [[ ${BOOKSTORE_FAILURES} == ${RUN_COUNT} ]] \
   && RESULT=1
 
-exit ${RESULT}
+# We fail the test if memory increase is large.
+detect_memory_leak "${START_MEMORY_USAGE}" "${SECOND_MEMORY_USAGE}" "${INCREASED_MEMORY_USAGE}"
+HAS_MEMORY_LEAK=$?
+echo "memory leak detect: ${HAS_MEMORY_LEAK}"
+
+exit $((${RESULT} + ${HAS_MEMORY_LEAK}))
