Create an Ubuntu 16-04 docker image for slave
- Enable Jenkins to use ubuntu image
- Updated install software to use multiple script per tool
- Storing built binaries in cloud storage

Change-Id: I13a0bd4e289cf7bf7e50c8ef0d2c99c6499970d9

diff --git a/script/all-utilities b/script/all-utilities
--- a/script/all-utilities
+++ b/script/all-utilities
@@ -26,10 +26,31 @@
 #
 ################################################################################
 #
-# Library of useful utilities.
+# Setting SUDO if not running as root.
+if [[ $UID -ne 0 ]]; then
+  SUDO=sudo
+fi
 
-GCLOUD="$(which gcloud)" || GCLOUD="${HOME}/google-cloud-sdk/bin/gcloud"
-BAZEL="$(which bazel)" || error_exit "Bazel not installed"
+[[ -z "${PLATFORM}" ]] && PLATFORM='debian-8'
+TOOLS_BUCKET=''
+
+# Library of useful utilities.
+function set_gcloud() {
+  export GCLOUD="$(which gcloud)" || export GCLOUD='/usr/lib/google-cloud-sdk/bin/gcloud'
+  export GSUTIL=$(which gsutil) || export GSUTIL='/usr/lib/google-cloud-sdk/bin/gsutil'
+}
+
+function set_bazel() {
+  export BAZEL="$(which bazel)" || export BAZEL='/usr/local/bin/bazel'
+}
+
+function set_wrk() {
+  export WRK="$(which wrk)" || export WRK='/usr/local/bin/wrk'
+}
+
+set_bazel
+set_gcloud
+set_wrk
 
 # Exit with a message and an exit code.
 # Arguments:
@@ -258,6 +279,36 @@ function activate_service_account() {
   trap "${GCLOUD} auth revoke ${service_account}" EXIT
 }
 
-if [[ $UID -ne 0 ]]; then
-  SUDO=sudo
-fi
+# Clearing apt cache.
+function clear_apt() {
+  echo 'Clearing apt source lists'
+  ${SUDO} rm -rf /var/lib/apt/lists/*
+  ${SUDO} apt-get update --fix-missing -qq && return 0
+  return 1
+}
+
+function update_tool() {
+  local tool_name="${1}"
+  local tool_version="${2}"
+  local local_path="${3}"
+  local remote_path="gs://${TOOLS_BUCKET}/${tool_name}/${tool_version}/${PLATFORM}/${tool_name}"
+
+  [[ -z "${TOOLS_BUCKET}" ]] && return 1
+  echo "Uploading ${local_path} to ${remote_path}."
+  ${GSUTIL} cp "${local_path}" "${remote_path}" \
+    || { echo "Failed to upload ${tool_name} to ${TOOLS_BUCKET}"; return 1; }
+  return 0
+}
+
+function get_tool() {
+  local tool_name="${1}"
+  local tool_version="${2}"
+  local local_path="${3}"
+  local remote_path="gs://${TOOLS_BUCKET}/${tool_name}/${tool_version}/${PLATFORM}/${tool_name}"
+
+  [[ -z "${TOOLS_BUCKET}" ]] && return 1
+  echo "Downloading ${remote_path} to ${local_path}."
+  ${GSUTIL} cp "${remote_path}" "${local_path}" \
+    || { echo "Failed to upload ${tool_name} to ${TOOLS_BUCKET}"; return 1; }
+  return 0
+}
diff --git a/script/tools/linux-install-clang b/script/tools/linux-install-clang
--- a/script/tools/linux-install-clang
+++ b/script/tools/linux-install-clang
@@ -26,21 +26,33 @@
 #
 ################################################################################
 #
-if ! [[ "${@}" =~ "-tunnel " ]]; then
-  if [[ -n "${JENKINS_TUNNEL}" ]]; then
-    TUNNEL="-tunnel ${JENKINS_TUNNEL}"
+# May require sudo login.
+
+if [[ "$(uname)" != "Linux" ]]; then
+  echo "Run on Linux only."
+  exit 1
+fi
+
+DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
+. ${DIR}/all-utilities || { echo "Cannot load Bash utilities" ; exit 1 ; }
+
+CLANG_VERSION='3.8'
+
+function install_clang() {
+  echo 'Installing clang'
+  clear_apt \
+  && ${SUDO} apt-get -qqy install {clang,clang-format}-"${CLANG_VERSION}" \
+  && ${SUDO} cp -f /usr/bin/clang-3.8 /usr/bin/clang \
+  && ${SUDO} cp -f /usr/bin/clang++-3.8 /usr/bin/clang++ \
+  && ${SUDO} cp -f /usr/bin/clang-format-3.8 /usr/bin/clang-format \
+  && return 0
+  return 1
+}
+
+function update_clang() {
+  local version="$(clang --version | grep -oh '[0-9]*\.[0-9]*\.[0-9]*')"
+  if ! [[ "${version}" =~ "${CLANG_VERSION}" ]]; then
+    retry install_clang || error_exit 'Cannot install clang.'
   fi
-fi
-
-if [[ -n "${JENKINS_URL}" ]]; then
-  URL="-url ${JENKINS_URL}"
-fi
-
-if [ -z "${JNLP_PROTOCOL_OPTS}" ]; then
-  echo "Warning: JnlpProtocol3 is disabled by default, use JNLP_PROTOCOL_OPTS to alter the behavior"
-  JNLP_PROTOCOL_OPTS="-Dorg.jenkinsci.remoting.engine.JnlpProtocol3.disabled=true"
-fi
-
-java ${JAVA_OPTS} ${JNLP_PROTOCOL_OPTS} \
-  -cp /usr/share/jenkins/slave.jar hudson.remoting.jnlp.Main \
-  -headless ${TUNNEL} ${URL} "${@}"
+  echo 'Clang is up to date.'
+}
diff --git a/script/tools/linux-install-gcloud b/script/tools/linux-install-gcloud
--- a/script/tools/linux-install-gcloud
+++ b/script/tools/linux-install-gcloud
@@ -26,21 +26,43 @@
 #
 ################################################################################
 #
-if ! [[ "${@}" =~ "-tunnel " ]]; then
-  if [[ -n "${JENKINS_TUNNEL}" ]]; then
-    TUNNEL="-tunnel ${JENKINS_TUNNEL}"
-  fi
+# May require ${SUDO} login.
+
+if [[ "$(uname)" != "Linux" ]]; then
+  echo "Run on Linux only."
+  exit 1
 fi
 
-if [[ -n "${JENKINS_URL}" ]]; then
-  URL="-url ${JENKINS_URL}"
-fi
+DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
+. ${DIR}/all-utilities || { echo "Cannot load Bash utilities" ; exit 1 ; }
 
-if [ -z "${JNLP_PROTOCOL_OPTS}" ]; then
-  echo "Warning: JnlpProtocol3 is disabled by default, use JNLP_PROTOCOL_OPTS to alter the behavior"
-  JNLP_PROTOCOL_OPTS="-Dorg.jenkinsci.remoting.engine.JnlpProtocol3.disabled=true"
-fi
 
-java ${JAVA_OPTS} ${JNLP_PROTOCOL_OPTS} \
-  -cp /usr/share/jenkins/slave.jar hudson.remoting.jnlp.Main \
-  -headless ${TUNNEL} ${URL} "${@}"
+GCLOUD_URL='https://dl.google.com/dl/cloudsdk/channels/rapid/google-cloud-sdk.zip'
+
+function install_gcloud() {
+  CLOUDSDK_PYTHON_SITEPACKAGES=1
+  ${SUDO} rm -rf /usr/lib/google-cloud-sdk \
+  && export CLOUDSDK_CORE_DISABLE_PROMPTS=1 \
+  && export CLOUDSDK_INSTALL_DIR=/usr/lib/ \
+  && curl https://sdk.cloud.google.com | ${SUDO} bash \
+  && export PATH="/usr/lib/google-cloud-sdk/bin:${PATH}" \
+  && set_gcloud \
+  && return 0
+  return 1
+}
+
+function check_and_install_gcloud() {
+  ${GCLOUD} --version && return 0
+  retry install_gcloud && return 0
+  return 1
+}
+
+function update_gcloud() {
+  check_and_install_gcloud \
+    || error_exit 'Could not install gcloud'
+  echo "Updating gcloud."
+  ${SUDO} sed -i -e 's/true/false/' /usr/lib/google-cloud-sdk/lib/googlecloudsdk/core/config.json
+  ${SUDO} ${GCLOUD} -q components update kubectl beta \
+    || error_exit 'Cannot update gcloud'
+}
+
diff --git a/script/tools/linux-install-nodejs b/script/tools/linux-install-nodejs
--- a/script/tools/linux-install-nodejs
+++ b/script/tools/linux-install-nodejs
@@ -26,21 +26,34 @@
 #
 ################################################################################
 #
-if ! [[ "${@}" =~ "-tunnel " ]]; then
-  if [[ -n "${JENKINS_TUNNEL}" ]]; then
-    TUNNEL="-tunnel ${JENKINS_TUNNEL}"
+# May require sudo login.
+
+if [[ "$(uname)" != "Linux" ]]; then
+  echo "Run on Linux only."
+  exit 1
+fi
+
+DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
+. ${DIR}/all-utilities || { echo "Cannot load Bash utilities" ; exit 1 ; }
+
+NODE_JS_VERSION='4.6.1'
+NODE_JS_URL="https://nodejs.org/dist/v${NODE_JS_VERSION}/node-v${NODE_JS_VERSION}-linux-x64.tar.xz"
+
+function install_node_js() {
+  echo 'Installing Node.js and npm.'
+  local node_tar="$(mktemp /tmp/XXXX.tar.xz)"
+  wget "${NODE_JS_URL}" -O "${node_tar}" \
+  && ${SUDO} tar -C /usr/local --strip-components 1 -xf "${node_tar}" \
+  && rm -rf "${node_tar}" \
+  && return 0
+  return 1
+}
+
+function update_node_js() {
+  local version="$(node --version | grep -oh '[0-9]*\.[0-9]*\.[0-9]*')"
+  if [[ "${version}" != "${NODE_JS_VERSION}" ]]; then
+    retry install_node_js \
+      || error_exit 'Cannot install node.js.'
   fi
-fi
-
-if [[ -n "${JENKINS_URL}" ]]; then
-  URL="-url ${JENKINS_URL}"
-fi
-
-if [ -z "${JNLP_PROTOCOL_OPTS}" ]; then
-  echo "Warning: JnlpProtocol3 is disabled by default, use JNLP_PROTOCOL_OPTS to alter the behavior"
-  JNLP_PROTOCOL_OPTS="-Dorg.jenkinsci.remoting.engine.JnlpProtocol3.disabled=true"
-fi
-
-java ${JAVA_OPTS} ${JNLP_PROTOCOL_OPTS} \
-  -cp /usr/share/jenkins/slave.jar hudson.remoting.jnlp.Main \
-  -headless ${TUNNEL} ${URL} "${@}"
+  echo 'Node.js is up to date.'
+}
