Release Qualification Improvements
+ Test create a more detailled status file including
  test id, unique id and date.
+ linux-test-vm-bookstore now creates its own log file.
+ json, tar and log files are now uploaded in one go for
  GKE, GCE tests.
+ Each test has a test id. For release qualification we can just
  look at the json file which all the information we need.
+ Created a new python script that will find all json files and validate
  the postsubmits.
+ Normalized test names accross files to help release owner find which
  test needs re-runs.

Change-Id: I73ff89c6b884e883d3ac7c417d180bed508f1187

diff --git a/script/all-utilities b/script/all-utilities
--- a/script/all-utilities
+++ b/script/all-utilities
@@ -122,19 +122,36 @@ function set_api_keys() {
 
 # Creates a simple Json Status file
 function create_status_file() {
-  local file_path="${1}"
-  local status="${2}"
+  local OPTARG ARG
+  local file_path=''
+  local test_status=''
+  local test_id=''
+  local run_id=''
+
+  while getopts ":f:s:t:r:" ARG; do
+    case ${ARG} in
+      f) file_path="${OPTARG}";;
+      s) test_tatus=${OPTARG};;
+      t) test_id="${OPTARG}";;
+      r) run_id="${OPTARG}";;
+      *) echo "Unrecognized argument: -${OPTARG}";;
+    esac
+  done
+
   mkdir -p "$(dirname "${file_path}")"
 
   cat > "${file_path}" <<__EOF__
 {
-  "scriptStatus": ${status},
+  "scriptStatus": ${test_status},
+  "testId": "${test_id}",
+  "date": "$(date +%s)",
+  "runId": "${run_id}",
   "headCommitHash": "$(git rev-parse --verify HEAD)"
 }
 __EOF__
 }
 
-# Extract run_id from test env json created from
+# Extract key from test env json created from
 # script/create-test-env-json script.
 # As an example, from this json
 # {
@@ -143,11 +160,12 @@ __EOF__
 # "run_description": "Commit message",
 # "owner": "John Doe"
 # }
-# This method will return test-id-1902
-function extract_run_id_from_test_env_file() {
-  local json_path="${1}"
+function extract_key_from_test_env_file() {
+  local key="${1}"
+  local json_path="${2}"
   cat "${json_path}" \
-    | python -c 'import json,sys;obj=json.load(sys.stdin);print obj["run_id"]'
+    | python -c "import json,sys;obj=json.load(sys.stdin);print obj['${key}']" \
+    || { echo "Could not extract ${key} from ${json_path}"; return 1; }
 }
 
 # Current gcloud account may not have permission to deploy an GAE Flex
diff --git a/script/jenkins-utilities b/script/jenkins-utilities
--- a/script/jenkins-utilities
+++ b/script/jenkins-utilities
@@ -228,12 +228,18 @@ function check_service() {
 
 # Run and upload logs
 function long_running_test() {
-  local host=${1}
+  local host="${1}"
   local duration_in_hour=${2}
-  local api_key=${3}
-  local esp_service=${4}
-  local remote_dir=${5}
-  local log_file="$(mktemp /tmp/XXXXXX.log)"
+  local api_key="${3}"
+  local esp_service="${4}"
+  local log_dir="${5}"
+  local test_id="${6}"
+  local run_id="${7}"
+  local test_type=''
+  [[ ${duration_in_hour} -gt 0 ]] && test_type='long-run-test_'
+  local final_test_id="${test_type}${test_id}"
+  local log_file="${log_dir}/${final_test_id}.log"
+  local json_file="${log_dir}/${final_test_id}.json"
   local status
 
   # Checking Service before starting the test.
@@ -249,24 +255,14 @@ function long_running_test() {
       -s "${esp_service}" | tee "${log_file}"
 
     status=${PIPESTATUS[0]}
-
-    echo "Uploading log to ${remote_dir}"
-    retry -n 3 ${GSUTIL} -h Content-Type:text/plain cp \
-      "${log_file}" \
-      "${remote_dir}/long-run-test.log"
-    [[ ${?} -eq 0 ]] || echo 'Failed to upload long-run-test.log'
   fi
 
-  echo "Uplading json to ${remote_dir}"
-  retry -n 3 ${GSUTIL} -h Content-Type:application/json cp - \
-    "${remote_dir}"/long-run-test.json <<__EOF__
-{
-  "scriptStatus": ${status},
-  "headCommitHash": "$(git rev-parse --verify HEAD)"
-}
-__EOF__
-  [[ ${?} -eq 0 ]] || echo 'Failed to upload long-run-test.json'
-  rm -f ${log_file}
+  create_status_file \
+    -f "${json_file}" \
+    -s ${status} \
+    -t "${final_test_id}" \
+    -r "${run_id}"
+
   return ${status}
 }
 
@@ -297,14 +293,10 @@ function upload_logs() {
   local remote_dir="${1}"
   local log_dir="${2}"
 
-  for log_file in `find "${log_dir}" -type f`; do
-    [[ -s "${log_file}" ]] || continue
-    local filename="${log_file##*/}"
-    echo "Uploading log ${log_file} to ${remote_dir}"
-    retry -n 3 ${GSUTIL} -h Content-Type:application/x-gtar cp \
-      "${log_file}" "${remote_dir}/${filename}"
-    [[ ${?} -eq 0 ]] || echo "Failed to upload ${filename}"
-  done
+  echo "Uploading content of ${log_dir} to ${remote_dir}"
+  retry -n 3 ${GSUTIL} -h 'Content-Type:text/plain' -m cp -r \
+    "${log_dir}" "${remote_dir}" \
+    || echo "Failed to upload ${log_dir}"
 }
 
 # End to End tests common options
diff --git a/script/linux-test-vm-bookstore b/script/linux-test-vm-bookstore
--- a/script/linux-test-vm-bookstore
+++ b/script/linux-test-vm-bookstore
@@ -125,17 +125,16 @@ $ROOT/script/linux-gae-instance -a ${APP_DIR}/app_esp.yaml \
     -v ${GAE_VERSION} -p ${PROJECT_ID} create \
   || error_exit "Failed to deploy ${GAE_VERSION} to ${PROJECT_ID}."
 
-function json_filename () {
+function test_filename () {
   local flex='on'
   local endpoints='on'
+  local test_type=''
 
-  if [[ "${ENABLE_FLEX}" == 'false' ]]; then
-    flex='off'
-  fi
-  if [[ "${ENABLE_ENDPOINTS}" == 'false' ]]; then
-    endpoints='off'
-  fi
-  echo "flex-${flex}-endpoints-${endpoints}"
+  [[ "${ENABLE_FLEX}" == 'false' ]] && flex='off'
+  [[ "${ENABLE_ENDPOINTS}" == 'false' ]] && endpoints='off'
+  [[ ${DURATION_IN_HOUR} -gt 0 ]] && test_type='long-run-test_'
+
+  echo "${test_type}flex-${flex}-endpoints-${endpoints}"
 }
 
 function cleanup() {
@@ -218,75 +217,90 @@ BOOKSTORE_FAILURES=0
 JWT_TOKEN="eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjMzYTY4MWIzNmI4OTgzOTEzYjA1ZjhkNWVhYjE2NWM2MDY5NGI2ZmMifQ.eyJpc3MiOiJsb2FkdGVzdEBlc3AtdGVzdC1jbGllbnQuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLCJzdWIiOiJsb2FkdGVzdEBlc3AtdGVzdC1jbGllbnQuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLCJhdWQiOlsidGVzdCIsImVzcC1sb2FkLXRlc3QuYXBwc3BvdC5jb20iLCJlc3AtbG9uZy1ydW4uYXBwc3BvdC5jb20iXSwiaWF0IjoxNDU3MTA5NzY1LCJleHAiOjI0NTcxMTMzNjV9.NzO4y_BkW5Dz7cwkMUzApBGwXtHwVVujhc4pxcODcFYB44mOzS49iHnikoRquBHB6tsCE61Y4GwK4Gdk7ng5-PFqUF6ctD6Onum4pMSH25DmqyI6kht4TSNiAHT1A2KhrBv7WFTMKYmn1SrvioLkiCH7XrxO2mTohr9yh2X8qvrGVj06OkdFp-3A7N3RFZouhGBWeGf1dBnXwB0MvlIVmi63rFnvLryCKFMb8aQgADSEDPVtdoSzDe_s2eIXucaLTRe0lgVr9E1vStmU147uI56v-ymREUC1GJTvhamSupfP56eJZ3ESivoFutFLKGjQvKRkahc_Rr4YfonlbiVGKA"
 
 RESULT=0  # succeed by default
+LOG_DIRECTORY="$(mktemp -d /tmp/XXXX_log_dir)"
+TEST_ID="$(test_filename)"
+LOG_FILE="${LOG_DIRECTORY}/${TEST_ID}.log"
+JSON_FILE="${LOG_DIRECTORY}/${TEST_ID}.json"
 
-while true; do
-  # Check that we are still calling the deployed version.
-  if ! check_deployed_version; then
-    RESULT=1
-    break
-  fi
+(
+  while true; do
+    # Check that we are still calling the deployed version.
+    if ! check_deployed_version; then
+      RESULT=1
+      exit ${RESULT}
+    fi
 
-  ((RUN_COUNT++))
+    ((RUN_COUNT++))
 
-  #######################
-  # Insert tests here
-  #######################
+    #######################
+    # Insert tests here
+    #######################
 
-  echo "Starting test run ${RUN_COUNT} at $(date)."
-  echo "Failures so far: Stress: ${STRESS_FAILURES}, Bookstore: ${BOOKSTORE_FAILURES}."
+    echo "Starting test run ${RUN_COUNT} at $(date)."
+    echo "Failures so far: Stress: ${STRESS_FAILURES}, Bookstore: ${BOOKSTORE_FAILURES}."
 
-  if [[ "${USE_LONG_LIFE_TOKEN}" == "false" ]]; then
-    # Need to re-generate token for each run, it expired in 1 hour.
-    JWT_TOKEN=$(${ROOT}/client/custom/gen-auth-token.sh -a ${SERVICE_NAME})
-  fi
-  echo "Auth token is: ${JWT_TOKEN}"
-  sed -e "s|\${API_KEY}|${API_KEY}|g" \
-      -e "s|\${HOST}|${HOST}|g" \
-      -e "s|\${POST_FILE}|${POST_FILE}|g" \
-      -e "s|\${JWT_TOKEN}|${JWT_TOKEN}|g" \
-      ${ROOT}/test/client/test_data.json.temp > ${ROOT}/test/client/test_data.json
-  cat ${ROOT}/test/client/test_data.json
+    if [[ "${USE_LONG_LIFE_TOKEN}" == "false" ]]; then
+      # Need to re-generate token for each run, it expired in 1 hour.
+      JWT_TOKEN=$(${ROOT}/client/custom/gen-auth-token.sh -a ${SERVICE_NAME})
+    fi
+    echo "Auth token is: ${JWT_TOKEN}"
+    sed -e "s|\${API_KEY}|${API_KEY}|g" \
+        -e "s|\${HOST}|${HOST}|g" \
+        -e "s|\${POST_FILE}|${POST_FILE}|g" \
+        -e "s|\${JWT_TOKEN}|${JWT_TOKEN}|g" \
+        ${ROOT}/test/client/test_data.json.temp > ${ROOT}/test/client/test_data.json
+    cat ${ROOT}/test/client/test_data.json
 
-  if [[ "${ENABLE_ENDPOINTS}" == "true" ]]; then
-    echo "Test bookstore with endpoints=on."
-    ${ROOT}/test/client/esp_bookstore_test.py \
-      --host=${HOST} --endpoints=true \
-      --api_key=${API_KEY} --auth_token=${JWT_TOKEN}
-  else
-    echo "Test bookstore with endpoints=off."
-    ${ROOT}/test/client/esp_bookstore_test.py \
-      --host=${HOST} --endpoints=false
-  fi
+    if [[ "${ENABLE_ENDPOINTS}" == "true" ]]; then
+      echo "Test bookstore with endpoints=on."
+      ${ROOT}/test/client/esp_bookstore_test.py \
+        --host=${HOST} --endpoints=true \
+        --api_key=${API_KEY} --auth_token=${JWT_TOKEN}
+    else
+      echo "Test bookstore with endpoints=off."
+      ${ROOT}/test/client/esp_bookstore_test.py \
+        --host=${HOST} --endpoints=false
+    fi
 
-  [[ ${RESULT} -eq 0 ]] \
-    || ((BOOKSTORE_FAILURES++))
+    [[ ${RESULT} -eq 0 ]] \
+      || ((BOOKSTORE_FAILURES++))
 
-  if [[ ${DURATION_IN_HOUR} -ne 0 ]]; then
-    echo "Starting stress test at $(date)."
-    ./esp_client.py --test=stress --test_data=${ROOT}/test/client/test_data.json \
-      || ((STRESS_FAILURES++))
-  fi
-  #######################
-  # End of test suite
-  #######################
+    if [[ ${DURATION_IN_HOUR} -ne 0 ]]; then
+      echo "Starting stress test at $(date)."
+      ./esp_client.py --test=stress --test_data=${ROOT}/test/client/test_data.json \
+        || ((STRESS_FAILURES++))
+    fi
+    #######################
+    # End of test suite
+    #######################
 
-  # Break if test has run long enough.
-  [[ $(date +"%s") -lt ${END_TIME} ]] || break
-done
+    # Break if test has run long enough.
+    [[ $(date +"%s") -lt ${END_TIME} ]] || break
+  done
 
-echo "Finished ${RUN_COUNT} test runs."
-echo "Failures: Stress: ${STRESS_FAILURES}, Bookstore: ${BOOKSTORE_FAILURES}."
+  echo "Finished ${RUN_COUNT} test runs."
+  echo "Failures: Stress: ${STRESS_FAILURES}, Bookstore: ${BOOKSTORE_FAILURES}."
 
-# We only fail the test if all bookstore runs failed.
-[[ ${BOOKSTORE_FAILURES} == ${RUN_COUNT} ]] \
-  && RESULT=1
+  # We only fail the test if all bookstore runs failed.
+  [[ ${BOOKSTORE_FAILURES} == ${RUN_COUNT} ]] \
+    && RESULT=1
+
+  exit ${RESULT}
+) | tee  "${LOG_FILE}"
+
+RESULT=${PIPESTATUS[0]}
 
 if [[ -n "${BUCKET}" ]] ; then
-  create_status_file "${HOME}/nginx-logs/"$(json_filename)".json" "${RESULT}"
+  create_status_file \
+    -f "${JSON_FILE}" \
+    -s "${RESULT}" \
+    -t "${TEST_ID}" \
+    -r "${GAE_VERSION}"
+
   echo "Uploading NGINX server logs to ${BUCKET}."
   ${ROOT}/script/linux-gae-instance \
-    -v "${GAE_VERSION}" -p "${PROJECT_ID}" -d "${HOME}/nginx-logs" nginx-logs \
-    && gsutil -h "Content-Type:text/plain" -m cp -r "${HOME}/nginx-logs" "${BUCKET}/${GAE_VERSION}" \
+    -v "${GAE_VERSION}" -p "${PROJECT_ID}" -d "${LOG_DIRECTORY}" nginx-logs \
+    && gsutil -h "Content-Type:text/plain" -m cp -r "${LOG_DIRECTORY}" "${BUCKET}/${GAE_VERSION}" \
     || error_exit "Cannot download NGINX logs."
 fi
 
