Fail tests only if all bookstore runs are failing.
This means that in order to qualify a release there should be at least
one successful run of esp-master jenkins project.

Change-Id: Id5414ded54bffa38e543969d7eefc9c442d94b23

diff --git a/script/linux-test-kb-long-run b/script/linux-test-kb-long-run
--- a/script/linux-test-kb-long-run
+++ b/script/linux-test-kb-long-run
@@ -124,4 +124,10 @@ done
 echo "Finished ${RUN_COUNT} test runs."
 echo "Failures: Stress: ${STRESS_FAILURES}, Bookstore: ${BOOKSTORE_FAILURES}."
 
-exit ${BOOKSTORE_FAILURES}
+RESULT=0
+
+# We only fail the test if all bookstore runs failed.
+[[ ${BOOKSTORE_FAILURES} == ${RUN_COUNT} ]] \
+  && RESULT=1
+
+exit ${RESULT}
