Only mark grpc stress test failed if only pass-through failed
Change-Id: I096df6e51fbab4773df5d8d7f1faf02c10cbadc1

diff --git a/script/linux-grpc-test-long-run b/script/linux-grpc-test-long-run
--- a/script/linux-grpc-test-long-run
+++ b/script/linux-grpc-test-long-run
@@ -173,4 +173,7 @@ popd > /dev/null
 echo "Finished ${RUN_COUNT} test runs."
 echo "Failures: pass-through: ${GRPC_STRESS_FAILURES}, transcode: ${HTTP_STRESS_FAILURES}."
 
-exit $((GRPC_STRESS_FAILURES + HTTP_STRESS_FAILURES))
+# Only mark test as failed if any pass-through tests failed.
+# This is to be consistent with other http stress tests.
+# All failure will be analyzed by release-engineers.
+exit ${GRPC_STRESS_FAILURES}
