Release Improvements and script cleanup.
* Each script creates a json file.
* Used already built binary for local performance.
* Gather logs from local performance test.
* Bash script cleanup.
* Using docker image created by jenkins for release.

Change-Id: I297715af170ce3294e8cde2370b4012edfbc52ad

diff --git a/script/linux-start-local-test b/script/linux-start-local-test
--- a/script/linux-start-local-test
+++ b/script/linux-start-local-test
@@ -27,10 +27,10 @@
 ################################################################################
 #
 
-[[ "$(uname)" == "Linux" ]] || { echo "Run on Linux only."; exit 1; }
+[[ "$(uname)" == 'Linux' ]] || { echo 'Run on Linux only.'; exit 1; }
 
 ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
-. ${ROOT}/script/all-utilities || { echo "Cannot load Bash utilities"; exit 1; }
+. "${ROOT}/script/all-utilities" || { echo 'Cannot load Bash utilities'; exit 1; }
 
 TEST_ENV=""
 # This variable can be set by -m option. If set to a positive value, the nginx
@@ -38,20 +38,35 @@ TEST_ENV=""
 # this script will skip running the loadtest client esp_client.py.
 MANUAL_TEST_DURATION_MINUTES=0
 
-while getopts m:t: arg; do
+function quit_nginx {
+  echo "Shutting down Nginx."
+  "${NGINX}" "${NGINX_ARGS[@]}" -s quit
+}
+
+function tar_logs() {
+  local tar_file="${1}"
+  local path_to_tar="${2}"
+  echo "Taring local logs from ${path_to_tar}."
+  tar czf "${tar_file}" "${path_to_tar}" \
+    || echo "Unable to tar {path_to_tar}."
+}
+
+
+while getopts :b:m:t: arg; do
   case ${arg} in
+    b) BUCKET="${OPTARG}";;
     m) MANUAL_TEST_DURATION_MINUTES="${OPTARG}";;
-    t) TEST_ENV="--test_env=$(realpath "${OPTARG}")";;
+    t) TEST_ENV="$(realpath "${OPTARG}")";;
   esac
 done
 
-echo "Installing Node.js and npm."
+echo 'Installing Node.js and npm.'
 wget https://storage.googleapis.com/apache_tarballs/node-v4.2.1-linux-x64.tar.gz \
-  || error_exit "Failed to download Node.js package."
+  || error_exit 'Failed to download Node.js package.'
 sudo tar -C /usr/local --strip-components 1 -xzf node-v4.2.1-linux-x64.tar.gz \
-  || error_exit "Failed to install Node.js."
+  || error_exit 'Failed to install Node.js.'
 
-echo "Starting backend."
+echo 'Starting backend.'
 pushd test/echo
 npm install
 node echo.js 2>&1 > /dev/null&
@@ -61,75 +76,79 @@ popd
 NGINX=${ROOT}/nginx-esp
 
 gsutil cp gs://client-secret-files/esp-load-test-08fcbb64ace1.json \
-    ${ROOT}/test/echo/gce-vm/client-secret.json \
+    "${ROOT}/test/echo/gce-vm/client-secret.json" \
   || error_exit "Failed to download credentials."
 
 set_api_keys
 API_KEY="${ESP_LOAD_TEST_API_KEY}"
 [[ -n "${API_KEY}" ]] || error_exit 'Could not set api key.'
-NGINX_CONFIG=${ROOT}/test/echo/gce-vm/nginx.conf
-PREFIX=${ROOT}/.nginx
+NGINX_CONFIG="${ROOT}/test/echo/gce-vm/nginx.conf"
+PREFIX="${ROOT}/.nginx"
 # clean up the error log before the run
-rm ${PREFIX}/logs/error.log
+rm "${PREFIX}/logs/error.log"
 
-(
-  echo "Building Endpoints Runtime."
-  cd ${ROOT} \
+
+NGINX_BAZEL_BIN="${ROOT}/bazel-bin/src/nginx/main/nginx-esp"
+if ! [[ -e "${NGINX_BAZEL_BIN}" ]]; then
+  echo 'Building Endpoints Runtime.'
+  cd "${ROOT}" \
     && bazel build --config=release //src/nginx/main:nginx-esp \
-    && cp -f "${ROOT}/bazel-bin/src/nginx/main/nginx-esp" "${NGINX}" \
-    || error_exit "Failed to build //src/nginx/main:nginx-esp"
-) \
-  || error_exit "Build failed, aborting."
+    || error_exit 'Failed to build //src/nginx/main:nginx-esp'
+fi
+cp -f "${NGINX_BAZEL_BIN}" "${NGINX}" \
+  || error_exit 'Error copying nginx-esp, aborting.'
 
-echo "Starting Endpoints Runtime."
+echo 'Starting Endpoints Runtime.'
 mkdir --parents --mode=777 "${PREFIX}/logs" \
-  || error_exit "Cannot create NGINX logs directory."
+  || error_exit 'Cannot create NGINX logs directory.'
 
 NGINX_ARGS=(-p "${PREFIX}" -c "${NGINX_CONFIG}" -g "pid ${PREFIX}/.nginx.pid;")
 
-${NGINX} "${NGINX_ARGS[@]}" -T  \
-  || error_exit "Nginx configuration test failed."
-${NGINX} "${NGINX_ARGS[@]}"
+"${NGINX}" "${NGINX_ARGS[@]}" -T  \
+  || error_exit 'Nginx configuration test failed.'
+"${NGINX}" "${NGINX_ARGS[@]}"
 
-echo "Constructing test data."
-SERVICE_NAME="echo-esp-load-test.cloudendpointsapis.com"
-JWT_TOKEN=$( ${ROOT}/client/custom/gen-auth-token.sh \
-    -s ${ROOT}/test/echo/esp-echo-client-secret-jwk.json \
-    -a ${SERVICE_NAME} )
+echo 'Constructing test data.'
+SERVICE_NAME='echo-esp-load-test.cloudendpointsapis.com'
+JWT_TOKEN="$("${ROOT}/client/custom/gen-auth-token.sh" \
+    -s "${ROOT}/test/echo/esp-echo-client-secret-jwk.json" \
+    -a "${SERVICE_NAME}")"
 POST_FILE="${ROOT}/test/data/8k.json"
-HOST="http://127.0.0.1:8090"
+HOST='http://127.0.0.1:8090'
 sed -e "s|\${API_KEY}|${API_KEY}|g" \
     -e "s|\${HOST}|${HOST}|g" \
     -e "s|\${POST_FILE}|${POST_FILE}|g" \
     -e "s|\${JWT_TOKEN}|${JWT_TOKEN}|g" \
-    ${ROOT}/test/client/test_data.json.temp > ${ROOT}/test/client/test_data.json
-cat ${ROOT}/test/client/test_data.json
+    "${ROOT}/test/client/test_data.json.temp" > "${ROOT}/test/client/test_data.json"
+cat "${ROOT}/test/client/test_data.json"
 
-function quit_nginx {
-  ${NGINX} "${NGINX_ARGS[@]}" -s quit
-}
+trap quit_nginx EXIT
 
 if [[ ${MANUAL_TEST_DURATION_MINUTES} -gt 0 ]]; then
-  echo "ESP listens at port 8090. You can start your manual test against it."
+  echo 'ESP listens at port 8090. You can start your manual test against it.'
   echo "ESP will quit after ${DURATION_MINUTES} minutes or by Ctrl-C."
   echo "NGINX error log can be found here: ${PREFIX}/logs/error.log"
-  trap quit_nginx EXIT
   sleep `expr "${MANUAL_TEST_DURATION_MINUTES}" \* 60`
 else
-  echo "Start basic testing"
-  pushd ${ROOT}/test/client
-  ./esp_client.py --test_data=${ROOT}/test/client/test_data.json ${TEST_ENV}
-  EXIT_STATUS=$?
+  echo 'Start basic testing'
+  pushd "${ROOT}/test/client"
+  ./esp_client.py \
+    --test_data="${ROOT}/test/client/test_data.json" \
+    --test_env="${TEST_ENV}"
+  EXIT_STATUS=${?}
   popd
 fi
 
-echo "Shutting down Nginx."
-${NGINX} "${NGINX_ARGS[@]}" -s quit
+# Quitting nginx before gathering logs
+quit_nginx
 
-echo "========================================================================"
-echo "NGINX error log: ${PREFIX}/logs/error.log"
-echo "========================================================================"
-cat "${PREFIX}/logs/error.log"
-echo "========================================================================"
+if [[ -n "${BUCKET}" ]] ; then
+  RUN_ID="$(extract_run_id_from_test_env_file "${TEST_ENV}")"
+  LOG_DIRECTORY="$(mktemp -d /tmp/log_dir_XXXX)"
+  create_status_file "${LOG_DIRECTORY}/local-performance.json" "${EXIT_STATUS}"
+  tar_logs "$(mktemp "${LOG_DIRECTORY}/perf-XXXX.tar.gz")" "${PREFIX}/logs/"
+  gsutil -h 'Content-Type:text/plain' -m cp -r "${LOG_DIRECTORY}" "${BUCKET}/${RUN_ID}" \
+    || echo 'Cannot upload logs.'
+fi
 
 exit ${EXIT_STATUS}
diff --git a/script/linux-test-vm-echo b/script/linux-test-vm-echo
--- a/script/linux-test-vm-echo
+++ b/script/linux-test-vm-echo
@@ -34,34 +34,34 @@
 # and auth_token_gen.
 # script/linux-install-test-client can be used to install them.
 
-if [[ "$(uname)" != "Linux" ]]; then
-  echo "Run on Linux only."
+if [[ "$(uname)" != 'Linux' ]]; then
+  echo 'Run on Linux only.'
   exit 1
 fi
 
 ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
-. ${ROOT}/script/all-utilities \
-  || { echo "Cannot load Bash utilities" ; exit 1 ; }
+. "${ROOT}/script/all-utilities" \
+  || { echo 'Cannot load Bash utilities' ; exit 1 ; }
 
-IMAGE_NAME=gcr.io/endpointsv2/endpoints-runtime-flex:debian-git-$(git log -1 --pretty=format:%H)
-PROJECT_ID=esp-load-test
+IMAGE_NAME="gcr.io/endpointsv2/endpoints-runtime-flex:debian-git-$(git log -1 --pretty=format:%H)"
+PROJECT_ID='esp-load-test'
 API_KEY=''
 TEST_ENV=''
 BUCKET=''
 
 while getopts a:i:p:t:b: arg; do
   case ${arg} in
-    a) API_KEY=${OPTARG};;
-    i) IMAGE_NAME=${OPTARG};;
-    p) PROJECT_ID=${OPTARG};;
-    t) TEST_ENV="--test_env=$(realpath "${OPTARG}")";;
+    a) API_KEY="${OPTARG}";;
+    i) IMAGE_NAME="${OPTARG}";;
+    p) PROJECT_ID="${OPTARG}";;
+    t) TEST_ENV="$(realpath "${OPTARG}")";;
     b) BUCKET="${OPTARG}";;
     *) echo "Invalid option: -${OPTARG}";;
   esac
 done
 
 if [[ -z "${API_KEY}" ]]; then
-  echo "Getting default API Key set."
+  echo 'Getting default API Key set.'
   set_api_keys
   API_KEY="${ESP_LOAD_TEST_API_KEY}"
   [[ -n "${API_KEY}" ]] \
@@ -70,22 +70,22 @@ fi
 
 TIME_VERSION="$(date +"%Y%m%d%H%M%S")"
 APP_VERSION="${IMAGE_NAME}-${TIME_VERSION}"
-GAE_VERSION="perf-test-echo-${TIME_VERSION}"
+GAE_VERSION="$(extract_run_id_from_test_env_file "${TEST_ENV}")"
 echo "API_KEY: ${API_KEY}"
 echo "PROJECT_ID: ${PROJECT_ID}"
 echo "IMAGE_NAME: ${IMAGE_NAME}"
 echo "APP_VERSION: ${APP_VERSION}"
 echo "GAE_VERSION: ${GAE_VERSION}"
 
-APP_DIR=${ROOT}/test/echo
+APP_DIR="${ROOT}/test/echo"
 
-echo "Replaces environment."
-sed -i "s|\${MY_PROJECT_ID}|${PROJECT_ID}|g" ${APP_DIR}/swagger.json
-sed -i "s|\${VERSION}|${APP_VERSION}|g" ${APP_DIR}/echo.js
-sed -i "s|\${IMAGE_NAME}|${IMAGE_NAME}|g" ${APP_DIR}/app_esp.yaml
+echo 'Replaces environment.'
+sed -i "s|\${MY_PROJECT_ID}|${PROJECT_ID}|g" "${APP_DIR}/swagger.json"
+sed -i "s|\${VERSION}|${APP_VERSION}|g" "${APP_DIR}/echo.js"
+sed -i "s|\${IMAGE_NAME}|${IMAGE_NAME}|g" "${APP_DIR}/app_esp.yaml"
 
-$ROOT/script/linux-gae-instance -a $ROOT/test/echo/app_esp.yaml \
-    -v ${GAE_VERSION} -p ${PROJECT_ID} create \
+"${ROOT}/script/linux-gae-instance" -a "${ROOT}/test/echo/app_esp.yaml" \
+    -v "${GAE_VERSION}" -p "${PROJECT_ID}" create \
   || error_exit "Failed to deploy ${GAE_VERSION} to ${PROJECT_ID}."
 
 trap "$ROOT/script/linux-gae-instance -v ${GAE_VERSION} -p ${PROJECT_ID} delete" EXIT
@@ -101,32 +101,38 @@ echo "Deployed version: ${DEPLOYED_VERSION}"
 [[ "${DEPLOYED_VERSION}" =~ .*${APP_VERSION}.* ]] \
   || error_exit "DEPLOYED_VERSION: ${DEPLOYED_VERSION} not matched with ${APP_VERSION}"
 
-echo "Verify that endpoints is enabled"
+echo 'Verify that endpoints is enabled'
 EXPECTED_RESPONSE=".*Method doesn't allow unregistered callers.*STATUS_CODE:401"
-[[ "$(curl -w "STATUS_CODE:%{http_code}" ${HOST}/echo)" =~ $EXPECTED_RESPONSE ]] \
+[[ "$(curl -w "STATUS_CODE:%{http_code}" "${HOST}/echo")" =~ ${EXPECTED_RESPONSE} ]] \
   || error_exit "ERROR: Endpoints is disabled on ${HOST}"
 
 SERVICE_NAME="echo-${PROJECT_ID}.cloudendpointsapis.com"
-JWT_TOKEN=$($ROOT/client/custom/gen-auth-token.sh -s $ROOT/test/echo/esp-echo-client-secret-jwk.json -a $SERVICE_NAME)
-POST_FILE="$ROOT/test/echo/esp-echo-client-secret-x509.json"
-sed -e "s|\${API_KEY}|$API_KEY|g" \
-    -e "s|\${HOST}|$HOST|g" \
-    -e "s|\${POST_FILE}|$POST_FILE|g" \
-    -e "s|\${JWT_TOKEN}|$JWT_TOKEN|g" \
-    $ROOT/test/client/test_data.json.temp > $ROOT/test/client/test_data.json
-cat $ROOT/test/client/test_data.json
+JWT_TOKEN="$("${ROOT}/client/custom/gen-auth-token.sh" \
+  -s "${ROOT}/test/echo/esp-echo-client-secret-jwk.json" \
+  -a "${SERVICE_NAME}")"
+POST_FILE="${ROOT}/test/echo/esp-echo-client-secret-x509.json"
+sed -e "s|\${API_KEY}|${API_KEY}|g" \
+    -e "s|\${HOST}|${HOST}|g" \
+    -e "s|\${POST_FILE}|${POST_FILE}|g" \
+    -e "s|\${JWT_TOKEN}|${JWT_TOKEN}|g" \
+    "${ROOT}/test/client/test_data.json.temp" > "${ROOT}/test/client/test_data.json"
+cat "${ROOT}/test/client/test_data.json"
 
 echo "Start perf testing"
-pushd $ROOT/test/client > /dev/null
-./esp_client.py --test_data=$ROOT/test/client/test_data.json ${TEST_ENV}
+pushd "${ROOT}/test/client" > /dev/null
+./esp_client.py \
+  --test_data="${ROOT}/test/client/test_data.json" \
+  --test_env="${TEST_ENV}"
 RESULT=${?}
 
 if [[ -n "${BUCKET}" ]] ; then
-  echo "Downloading NGINX server logs."
-  ${ROOT}/script/linux-gae-instance \
-    -v "${GAE_VERSION}" -p "${PROJECT_ID}" -d "${HOME}/echo-nginx-logs" nginx-logs \
-  && gsutil -h "Content-Type:text/plain" -m cp -r "${HOME}/echo-nginx-logs" "${BUCKET}/${GAE_VERSION}" \
-  || error_exit "Cannot download NGINX logs."
+  LOG_DIRECTORY="${HOME}/nginx-logs"
+  create_status_file "${LOG_DIRECTORY}/flex-performance.json" "${RESULT}"
+  echo "Uploading NGINX server logs."
+  "${ROOT}/script/linux-gae-instance" \
+    -v "${GAE_VERSION}" -p "${PROJECT_ID}" -d "${LOG_DIRECTORY}" nginx-logs \
+  && gsutil -h 'Content-Type:text/plain' -m cp -r "${LOG_DIRECTORY}" "${BUCKET}/${GAE_VERSION}" \
+  || error_exit 'Cannot upload NGINX logs.'
 fi
 
 exit ${RESULT}
