Enabling hazelcast in Jenkins.
Change-Id: I561d5d994e20e672ac53d1c785a5e5c71beaf945

diff --git a/script/presubmits b/script/presubmits
--- a/script/presubmits
+++ b/script/presubmits
@@ -28,6 +28,7 @@
 #
 
 ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
+. ${ROOT}/script/all-utilities || { echo "Cannot load all-utilities"; exit 1; }
 
 function check_files() {
   # Check code styl and headers
@@ -44,7 +45,7 @@ function test_service_control() {
   echo 'Building, running integration tests for Service Control'
   pushd "${ROOT}/third_party/service-control-client-cxx"
   dirs
-  bazel test --test_output=errors :all \
+  "${BAZEL}" test "${BAZEL_ARGS}" --test_output=errors :all \
     || { echo 'Failed to build service control tests'; return 1; }
   popd
 }
@@ -60,7 +61,7 @@ function build_and_test() {
     error="${message} with config ${config}"
   fi
   echo "${message}..."
-  bazel test --test_output=errors ${config_flag} \
+  "${BAZEL}" test "${BAZEL_ARGS}" --test_output=errors ${config_flag} \
     //src/... //test/src/... //third_party:all || \
     { echo "${error}..."; return 1; }
 }
@@ -93,7 +94,7 @@ function coverage() {
 
 function docker_tests() {
   echo 'Building a debian package...'
-  bazel build --config=release //src/nginx/main:endpoints-server-proxy || \
+  "${BAZEL}" build "${BAZEL_ARGS}" --config=release //src/nginx/main:endpoints-server-proxy || \
     { echo  'Building the debian package failed'; return 1; }
 
   echo 'Running Docker test...'
