Adding fetch and retries for bazel builds.
Change-Id: Icb870fca05bfbfc7d11051774cd1715dd9c0d3c0

diff --git a/script/presubmits b/script/presubmits
--- a/script/presubmits
+++ b/script/presubmits
@@ -45,9 +45,10 @@ function test_service_control() {
   echo 'Building, running integration tests for Service Control'
   pushd "${ROOT}/third_party/service-control-client-cxx"
   dirs
-  "${BAZEL}" build ${BAZEL_ARGS} --test_output=errors :all \
-    || { echo 'Failed to build service control tests'; return 1; }
-  "${BAZEL}" test --test_output=errors :all \
+
+  retry -n 3 ${BAZEL} fetch :all \
+    && retry -n 2 ${BAZEL} build ${BAZEL_ARGS} :all \
+    && ${BAZEL} test --test_output=errors :all \
     || { echo 'Failed to run service control tests'; return 1; }
   popd
 }
@@ -63,12 +64,12 @@ function build_and_test() {
     error="${message} with config ${config}"
   fi
   echo "${message}..."
-  "${BAZEL}" build ${BAZEL_ARGS} --test_output=errors ${config_flag} \
-    //src/... //test/src/... //third_party:all || \
-    { echo "${error}..."; return 1; }
-  "${BAZEL}" test --test_output=errors ${config_flag} \
-    //src/... //test/src/... //third_party:all || \
-    { echo "${error}..."; return 1; }
+  retry -n 3 ${BAZEL} fetch //src/... //test/src/... //third_party:all \
+    && retry -n 2 ${BAZEL} build ${BAZEL_ARGS} ${config_flag} \
+      //src/... //test/src/... //third_party:all \
+    && ${BAZEL} test --test_output=errors ${config_flag} \
+      //src/... //test/src/... //third_party:all \
+    || { echo "${error}..."; return 1; }
 }
 
 function asan() {
@@ -93,23 +94,25 @@ function coverage() {
   # will be uploaded to a bucket.
   mkdir -p "${HOME}/artifacts"
   ${ROOT}/script/linux-run-coverage -s ${HOME}/artifacts/coverage.summary \
-    -t ${HOME}/artifacts/coverage.tar.gz || \
-    { echo  'Coverage failed.'; return 1; }
+    -t ${HOME}/artifacts/coverage.tar.gz \
+    || { echo  'Coverage failed.'; return 1; }
 }
 
 function docker_tests() {
   echo 'Building a debian package...'
-  "${BAZEL}" build ${BAZEL_ARGS} --config=release //src/nginx/main:endpoints-server-proxy || \
-    { echo  'Building the debian package failed'; return 1; }
+  retry -n 3 ${BAZEL} fetch //src/nginx/main:endpoints-server-proxy \
+  && retry -n 2 ${BAZEL} build ${BAZEL_ARGS} --config=release \
+    //src/nginx/main:endpoints-server-proxy \
+    || { echo  'Building the debian package failed'; return 1; }
 
   echo 'Running Docker test...'
   "${ROOT}/test/docker/docker_test.sh" -d \
-    "${ROOT}/bazel-bin/src/nginx/main/endpoints-server-proxy.deb" || \
-    { echo  'Docker test failed'; return 1; }
+    "${ROOT}/bazel-bin/src/nginx/main/endpoints-server-proxy.deb" \
+    || { echo  'Docker test failed'; return 1; }
 
   echo 'Running Generic docker test...'
   "${ROOT}/test/docker/generic_docker_test.sh" -d \
-    "${ROOT}/bazel-bin/src/nginx/main/endpoints-server-proxy.deb" || \
-    { echo  'Generic docker test failed'; return 1; }
+    "${ROOT}/bazel-bin/src/nginx/main/endpoints-server-proxy.deb" \
+    || { echo  'Generic docker test failed'; return 1; }
 }
 
