Improve build time
Change-Id: I404c589a58baa9ba873f23ba9a4f8a685841f204

diff --git a/script/presubmits b/script/presubmits
--- a/script/presubmits
+++ b/script/presubmits
@@ -45,8 +45,10 @@ function test_service_control() {
   echo 'Building, running integration tests for Service Control'
   pushd "${ROOT}/third_party/service-control-client-cxx"
   dirs
-  "${BAZEL}" test ${BAZEL_ARGS} --test_output=errors :all \
+  "${BAZEL}" build ${BAZEL_ARGS} --test_output=errors :all \
     || { echo 'Failed to build service control tests'; return 1; }
+  "${BAZEL}" test --test_output=errors :all \
+    || { echo 'Failed to run service control tests'; return 1; }
   popd
 }
 
@@ -61,7 +63,10 @@ function build_and_test() {
     error="${message} with config ${config}"
   fi
   echo "${message}..."
-  "${BAZEL}" test ${BAZEL_ARGS} --test_output=errors ${config_flag} \
+  "${BAZEL}" build ${BAZEL_ARGS} --test_output=errors ${config_flag} \
+    //src/... //test/src/... //third_party:all || \
+    { echo "${error}..."; return 1; }
+  "${BAZEL}" test --test_output=errors ${config_flag} \
     //src/... //test/src/... //third_party:all || \
     { echo "${error}..."; return 1; }
 }
