add spell check tool (#662)
* add spell check tool

* add spell check tool

* add skipped files from third_party and move spelling check tool to tools/spelling

* add skip files

* move check location

* move check location

diff --git a/script/robot-style b/script/robot-style
--- a/script/robot-style
+++ b/script/robot-style
@@ -29,6 +29,8 @@
 ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
 . ${ROOT}/script/all-utilities || { echo "Cannot load Bash utilities" ; exit 1 ; }
 
+
+
 CLANG_FORMAT="$(which clang-format-7)"
 
 pushd ${ROOT} > /dev/null
@@ -43,5 +45,7 @@ if [[ "${#CHANGED_FILES}" -ne 0 ]]; then
   echo "Files not formatted: ${CHANGED_FILES[@]}"
   exit 1
 fi
+
+. ${ROOT}/tools/spelling/check_spelling.sh check || { echo "Find spelling error" ; exit 1 ; }
 
 popd
