Merge from master to firebase branch (#114)
* Fixed bazel install

Change-Id: Ic573e8e4cc2900fa44dfa5c67d6728c58283b649

* Make docker slaves consistent with jenkinsci/slave

Change-Id: I6251e93ca7f9e588a552fbf5562d0ec24534480a

* Align with latest istio/proxy. (#73)

* Support HEAD request in transcoding (#74)

* Support HEAD request in transcoding

* Removed unused variables

* Fixing bazel install for ubuntu salve

Change-Id: I184624d166dd49ccd4242f3bcfc54b1182216909

* Use open-sourced scripts (#76)

* Use open-sourced scripts

* Add a workaround PEX issue

* Update to istio/proxy with mixer_client integration. (#78)

* Align with istio/proxy. (#79)

* Align with istio/proxy.

Change-Id: Ic175022bffc559bbc07bea823fde38a5bebc654c

* Update go file.

Change-Id: If0fd2a52b5b43fecc6b5ec4a1ad2864877de5b17

* Fix debian jessie package issue

* Fixes typo in script

* Modify test justification. (#83)

* Update NGINX to 1.11.9 (#75)

* Update NGINX to 1.11.9

* Remove mixer_client repo. (#85)

* Revert "Update NGINX to 1.11.9" (#86)

* Use grpc-go for interop tests (#88)

* fix grpc docker build script (#90)

* Upgrade bazel to 0.4.4 (#92)

* Upgrade bazel to 0.4.4

* Update istio/proxy for GRPC v1.1.1 (#89)

* Fix proxy_flow to align grpc 1.1.1

* Fix ProxyFlow leak (#93)

* Basic GRPC request compression support (#94)

* Remove undefined flag of Go stress client (#95)

* t-test changes to check that x-endpoint-api-userinfo is received by grpc (#96)

service.

* Fix typo (#97)

Change-Id: Idff7a0f23d013f1d67e6cb3c890c54fc0b21ef2e

* not to use api_key if service is not activated. (#98)

* Escape run description

Change-Id: I6a66f9be92314218ee6a19b2d82897b6c55c42d2

* Fix grpc interop stress test script. (#103)

* try to escape json again. (#106)

* Add t test for fail wrong api key. (#104)

Change-Id: I0ea9ed4ba94f13283616eae00b93f067f9c00cf5

* Allow grpc interop stress test fail once. (#105)

Change-Id: I5a090eae45c1d9b7d0641b2f09757bb373746aa1

* Update to latest endpoints-tool. (#110)

* Deprecate x-security (#101)

* Deprecate x-security

* Add one more swagger file

* Update swagger.yaml file also.

* Fix api_key

* Fix indentation

* Update api keys correctly

* Fix indentation

* Update CHANGELOG (#112)

* Update version number to 1.2.0. (#111)

diff --git a/script/test-grpc-interop b/script/test-grpc-interop
--- a/script/test-grpc-interop
+++ b/script/test-grpc-interop
@@ -28,7 +28,12 @@
 #
 
 # This script runs a grpc interop long-running test.
-# It requires bazel build //test/grpc:all
+# It requires bazel build following targets:
+#   //test/grpc:all
+#   @org_golang_google_grpc//stress/metrics_client
+#   @org_golang_google_grpc//interop/server
+#   @org_golang_google_grpc//stress/client
+#set -x
 
 ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
 . ${ROOT}/script/all-utilities \
@@ -36,9 +41,8 @@ ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
 
 HOST=''
 DURATION_IN_HOUR=0
-RUN_LENGTH=120
 TEST_CASES='empty_unary:10,large_unary:10,'
-TEST_CASES+='empty_stream:10,client_streaming:10,half_duplex:10,ping_pong:20,server_streaming:10,'
+TEST_CASES+='empty_stream:10,client_streaming:10,ping_pong:20,server_streaming:10,'
 TEST_CASES+='status_code_and_message:10,custom_metadata:10'
 
 while getopts :h:l:t: arg; do
@@ -52,16 +56,6 @@ done
 
 [[ -n "${HOST}" ]] || error_exit 'Please specify a host with -h option.'
 
-function print_test_metrics() {
-  local start_time=$(date +"%s")
-  while true; do
-    sleep 10
-    local curr_time=$(date +"%s")
-    echo -n "QPS report at $((curr_time - start_time)) seconds:"
-    $ROOT/bazel-bin/test/grpc/interop-metrics-client --total_only
-  done
-}
-
 # Waits for the proxy and backend to start.
 HOST_IP=${HOST%:*}
 HOST_PORT=${HOST#*:}
@@ -70,50 +64,52 @@ retry $ROOT/bazel-bin/test/grpc/interop-client --server_port "${HOST_PORT}" \
           --server_host "${HOST_IP}" \
   || error_exit 'Failed to send one request, the proxy did not start properly.'
 
+DURATION_IN_SEC=$((DURATION_IN_HOUR * 60 * 60))
+[[ ${DURATION_IN_SEC} -gt 120 ]] || DURATION_IN_SEC=120
+
 echo "Starts interop stress test at $(date)."
-echo "Test during is: $((DURATION_IN_SECONDS / 60)) minutes."
+echo "Test during is: $((DURATION_IN_SEC / 60)) minutes."
 echo "Test cases are: ${TEST_CASES}"
 
-# Start a background print job.
-print_test_metrics&
-PRINT_JOB=$!
-trap "kill ${PRINT_JOB}" EXIT
+# Start a background test client job.
+$ROOT/bazel-bin/external/org_golang_google_grpc/stress/client/client \
+  --server_addresses "${HOST}" \
+  --num_channels_per_server 200 \
+  --num_stubs_per_channel 1 \
+  --test_cases "${TEST_CASES}" 2> /dev/null&
+TEST_JOB=$!
+trap "kill ${TEST_JOB}" EXIT
 
 START_TIME=$(date +"%s")
-END_TIME=$((START_TIME + DURATION_IN_HOUR * 60 * 60))
+END_TIME=$((START_TIME + DURATION_IN_SEC))
 RUN_COUNT=0
-SUCCESS_TIME=0
+FAIL_COUNT=0
 
 detect_memory_leak_init "http://${HOST}"
 
 while true; do
   CURR_TIME=$(date +"%s")
-  echo "Test time: $((CURR_TIME - START_TIME)) seconds, success time: ${SUCCESS_TIME} seconds."
   ((RUN_COUNT++))
 
-  timeout $((RUN_LENGTH + 10)) $ROOT/bazel-bin/test/grpc/interop-stress-client \
-    --server_addresses "${HOST}" \
-    --test_duration_secs "${RUN_LENGTH}" \
-    --num_channels_per_server 200 \
-    --num_stubs_per_channel 1 \
-    --do_not_abort_on_transient_failures false \
-    --test_cases "${TEST_CASES}" \
-  && ((SUCCESS_TIME += RUN_LENGTH))
-
-  detect_memory_leak_check ${RUN_COUNT}
+  sleep 10
+  METRIC_RESULT=$("$ROOT/bazel-bin/external/org_golang_google_grpc/stress/metrics_client/metrics_client" \
+    --total_only --metrics_server_address=localhost:8081 2>&1)
+  QPS=$(echo ${METRIC_RESULT}|awk '{print $NF}')
+  echo "Metric report at $((CURR_TIME - START_TIME)) seconds: ${QPS} qps"
+  # Count non zero QPS as success.
+  [[ ${QPS} -gt 100 ]] || ((FAIL_COUNT++))
 
   # Break if test has run long enough.
   [[ $(date +"%s") -lt ${END_TIME} ]] || break
 done
 
-END_TIME=$(date +"%s")
-echo "Total test time: $((END_TIME - START_TIME)) seconds, success time: ${SUCCESS_TIME} seconds at $(date)."
+echo "Total test count: ${RUN_COUNT}, failed count: ${FAIL_COUNT}."
 
-TOTAL_TIME=$((END_TIME - START_TIME))
-FAILURE_TIME=$((TOTAL_TIME - SUCCESS_TIME))
 # If failure time is more than %5 of total test time, mark failed.
 RESULT=0
-[[ ${FAILURE_TIME} -gt $((TOTAL_TIME / 20)) ]] && RESULT=1
+if [[ ${FAIL_COUNT} -gt $((RUN_COUNT / 20)) && ${FAIL_COUNT} -gt 1 ]] ; then
+    RESULT=1
+fi
 
 # We fail the test if memory increase is large.
 detect_memory_leak_final && MEMORY_LEAK=0 || MEMORY_LEAK=1
