Allow esp presubmit test on istio/proxy PR (#49)
* Add variable for ISTIO_PROXY sha and reformat WORKSPACE file

Change-Id: Id26017a9eb13b3d452f2606e0efa89cd51324484

* Added support for testing remote submodules

Change-Id: I68ffa69ec42808c6cbca36feb8aa0e0b80ab17ba

* Setup git for every node.

Change-Id: Iec9b0cd6fc789f6d72ed4db6d61e5ba4f148e77f

diff --git a/script/update-submodules b/script/update-submodules
--- a/script/update-submodules
+++ b/script/update-submodules
@@ -27,24 +27,40 @@
 ################################################################################
 #
 
-DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
-. ${DIR}/jenkins-utilities \
-  || { echo "Cannot load Bash utilities" ; exit 1 ; }
+ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
+. ${ROOT}/script/all-utilities || { echo "Cannot load Bash utilities"; exit 1; }
 
-while getopts :c:z: arg; do
+function update_workspace() {
+  local key="${1}"
+  local sha="${2}"
+
+  sed -i -e "s|${key}\s=.*|${key} = \"${sha}\"|" "${ROOT}/WORKSPACE" \
+    || error_exit "Could not update WORKSPACE for ${key}."
+}
+
+function commit_workspace() {
+  local key="${1}"
+
+  git add "${ROOT}/WORKSPACE" \
+    && git commit -m "Updates ${key} in WORKSPACE" \
+    || error_exit "Could not create commit for ${key} update in WORKSPACE."
+}
+
+while getopts :s: arg; do
   case ${arg} in
-    c) CLUSTER="${OPTARG}";;
-    z) ZONE="${OPTARG}";;
-    *) error_exit "Invalid option: -${OPTARG}";;
+    s) SUBMODULES="${OPTARG}";;
+    *) echo "Invalid option: -${OPTARG}";;
   esac
 done
 
-[[ -z "${CLUSTER}" ]] && error_exit 'CLUSTER should be set.'
-[[ -z "${ZONE}" ]] && error_exit 'ZONE should be set.'
-
 set_git
-script/linux-prep-machine || error_exit 'Could not prep machine.'
-script/linux-install-software || error_exit 'Could not update the tools.'
-retry -n 5 ${GCLOUD} config set compute/zone "${ZONE}"
-retry -n 5 ${GCLOUD} container clusters get-credentials "${CLUSTER}"
+
+# SUBMODULES if of the form KEY1:SHA1,KEY2:SHA2
+IFS=',' read -ra SUBMODULES <<< "${SUBMODULES}"
+for submodule in "${SUBMODULES[@]}"; do
+  key="${submodule%:*}"
+  sha="${submodule##*:}"
+  update_workspace "${key}" "${sha}"
+  commit_workspace "${key}"
+done
 
